---
Name: sscounter
After:
  - '#silverstripe-react'
---
SilverStripe\Admin\LeftAndMain:
  extra_requirements_javascript:
    - 'marczhermo/sscounter: client/dist/main.js'
    - 'marczhermo/sscounter: client/dist/remoteEntry.js'
#    - 'http://localhost:8088/remoteEntry.js'
  extra_requirements_css:
    - 'marczhermo/sscounter: client/dist/styles/bundle.css'
